buybid_admin/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope module: 'spree' do
    namespace :admin do
      resources :products do
        member do
          get '/set_visible', to: "products#toggle_visible", as: :toggle_visible
          get '/set_popular', to: "products#toggle_popular", as: :toggle_popular
        end
      end
    end
  end

  scope module: 'buybid' do
    namespace :admin do
      resources :sellers do
        resources :images do
          get '/set_logo', to: "images#set_logo", as: :set_logo
        end
        collection do
          get '(/:list_type)', to: "sellers#index", as: ""
          get '/new/(:list_type)', to: "sellers#new", as: "new"
          post '/(:list_type)', to: "sellers#create", as: :create
        end

        member do
          put '(/:list_type)', to: "sellers#update", as: :update
          get '/edit/(:list_type)', to: "sellers#edit", as: "edit"
          get '/set_visible(/:list_type)', to: "sellers#toggle_popular", as: :toggle_popular
          get '/set_popular(/:list_type)', to: "sellers#toggle_visible", as: :toggle_visible
          get '/edit_rating_and_evals(/:list_type)', to: "sellers#edit_rating_and_evals", as: :edit_rating_and_evals
          get '/contacts(/:list_type)', to: "sellers#contacts", as: :contacts
          get '/contacts/new(/:list_type)', to: "sellers#new_contact", as: :new_contact
          get '/products(/:list_type)', to: "sellers#products", as: :products
          post '/contacts(/:list_type)', to: "sellers#create_contact", as: :create_contact
          patch '/contacts/:contact_id(/:list_type)', to: "sellers#update_contact", as: :update_contact
          delete '/contacts/:contact_id(/:list_type)', to: "sellers#destroy_contact", as: :destroy_contact
        end
      end
    end
  end
  mount Spree::Core::Engine, at: '/'
end

buybid_admin/app/controllers/buybid/admin/sellers_controller.rb
# frozen_string_literal: true

module Buybid
  module Admin
    class SellersController < Spree::Admin::BaseController
      before_action :set_seller, only: %i[show edit update destroy toggle_visible toggle_popular edit_details edit_rating_and_evals contacts update_contact new_contact create_contact products]
      before_action :set_contact, only: %i[update_contact destroy_contact]
      before_action :filter_sellers, :load_main_category_id, only: [:index]
      before_action :set_list_type
      before_action :set_default_values_for_edit, only: [:edit]
      before_action :set_default_values_for_new, only: [:new]

      def index; end

      def show; end

      def products
        @products = @seller.spree_products.all
      end

      def create
        @seller = Buybid::Seller.new(seller_params.except(:attachment, :category_taxon_ids))
        respond_with(@seller) do |format|
          # Validate attachment type before saving
          if @seller.set_logo(seller_params[:attachment]) && @seller.save
            @seller.set_visible_and_popular(seller_params[:visible], seller_params[:popular])
            @seller.set_type(seller_params[:auction], seller_params[:shop], seller_params[:partner], seller_params[:store])
            @seller.update_category(seller_params[:category_taxon_ids])
            @seller.set_main_category_id(seller_params[:main_category_id]) if seller_params[:main_category_id].present?

            format.html { redirect_to admin_sellers_path(@list_type), notice: 'Seller is successfully created!' }
            format.json { render :index, status: :created, location: @seller }
          else
            flash[:error] = @seller.errors.full_messages
            format.html { render :new, locals: { category_taxon_ids: seller_params[:category_taxon_ids] } }
            format.json { render json: @seller.errors.full_messages, status: :unprocessable_entity }
          end
        end
      end

      def new
        @seller = Buybid::Seller.new
      end

      def edit
        @seller = Buybid::Seller.find_by_id(params[:id])
      end

      def update
        @seller.update_attributes(seller_params.except(:category_taxon_ids, :attachment))
        respond_to do |format|
          if  @seller.set_logo(seller_params[:attachment]) && @seller.save
            @seller.set_visible_and_popular(seller_params[:visible], seller_params[:popular])
            @seller.update_category(seller_params[:category_taxon_ids])
            @seller.set_main_category_id(seller_params[:main_category_taxon_id]) if seller_params[:main_category_taxon_id].present?
            format.html { redirect_to admin_sellers_path(@list_type), notice: "Seller #{@seller.name} is successfully udapted" }
            format.json { render :show, status: :updated, location: @seller }
          else
            flash[:error] = @seller.errors.full_messages
            format.html { render 'edit' }
            format.json { render :edit, status: :edit, location: @seller }
          end
        end
      end

      # Soft delete the seller, the seller records still in the db. However, the delete button still intact
      def destroy
        respond_to do |format|
          if @seller.mark_as_deleted
            format.html { redirect_to admin_sellers_path(@list_type), notice: "Seller #{@seller.name} is deleted successfully!" }
            format.json { render :index, status: :success }
          else
            format.html { redirect_to '/admin/sellers/partners', notice: "Seller #{@seller.name} cannot be deleted!. #{@seller.errors.full_messages}" }
            format.json { render :index, status: :unprocessable_entity }
          end
        end
      end

      # If set to false, seller will no longer be visible on the client
      def toggle_visible
        @seller.toggle(:visible)

        respond_to do |format|
          if @seller.save
            format.html { redirect_to admin_sellers_path(@list_type), notice: "Seller #{@seller.name}'s visibility is now set to #{@seller.visible?}" }
          else
            flash[:error] = "Seller #{@seller.name} failed to set visible to #{!@seller.visible}. Error: #{@seller.errors.full_messages}"
            format.html { redirect_to admin_sellers_path(@list_type) }
          end
        end
      end

      # If set to false, seller will no longer be popular on the client
      def toggle_popular
        @seller.toggle(:popular)

        respond_to do |format|
          if @seller.save
            format.html { redirect_to admin_sellers_path(@list_type), notice: "Seller #{@seller.name}'s popularity is now set to #{@seller.popular?}" }
          else
            flash[:error] = "Seller #{@seller.name} failed to set visible to #{!@seller.popular}. Error: #{@seller.errors.full_messages}"
            format.html { redirect_to admin_sellers_path(@list_type) }
          end
        end
      end

      def edit_rating_and_evals; end

      # show all the contacts of a specific seller
      def contacts
        @contacts = @seller.get_contacts
      end

      # Create a new contact for each seller
      def new_contact
        @contact = Spree::Address.new
      end

      # Create a new contact and save it to the database
      def create_contact
        @contact = Spree::Address.new(contact_params)
        # Currently for demo, I will leave the country id to be 1, later update will be noticed!
        hard_code_contact(contact_params)
        respond_to do |format|
          if @contact.save
            @seller.spree_addresses << @contact
            format.html { redirect_to contacts_admin_seller_path, notice: "Contacts #{@contact.firstname} #{@contact.lastname} is successfully created!" }
          else
            flash[:error] = @contact.errors.full_messages
            format.html { render :new_contact }
            format.json { render :new_contact, status: :unprocessable_entity }
          end
        end
      end

      # Update the contact of each individual seller
      def update_contact
        # hard_code_contact(contact_params)
        respond_to do |format|
          if @contact.update_attributes(contact_params)
            format.html { redirect_to contacts_admin_seller_path(@seller), notice: 'Contact has successfully been updated!' }
          else
            flash[:error] = @contact.errors.full_messages
            format.html { redirect_to contacts_admin_seller_path(@seller), notice: 'Contact failed to be saved!' }
            format.json { render :contacts, status: :unprocessable_entity }
          end
        end
      end

      # Update the new contact record into the database
      def destroy_contact
        respond_to do |format|
          if @contact.destroy
            format.html { redirect_to contacts_admin_seller_path, notice: "Contacts #{@contact.firstname} #{@contact.lastname} is successfully destroy!" }
          else
            format.html { redirect_to contacts_admin_seller_path, notice: "Contacts #{@contact.firstname} #{@contact.lastname} cannot be updated #{@contact.errors.full_messages}" }
          end
        end
      end

      private

      # Using the collection to query sellers based on the search results
      def filter_sellers
        params[:q] ||= {}
        params[:q][:visible] ||= '0'
        params[:q][:popular] ||= '0'
        params[:q][:main_category_id] ||= nil
        params[:q][:account_code] ||= nil

        @seller = if params[:list_type].chomp('s') == BuybidCommon::BusinessNames::AUCTION
          Buybid::Seller.auction
        elsif params[:list_type].chomp('s') == BuybidCommon::BusinessNames::SHOP
          Buybid::Seller.shop
        elsif params[:list_type].chomp('s') == BuybidCommon::BusinessNames::PARTNER
          Buybid::Seller.partner
        elsif params[:list_type].chomp('s') == BuybidCommon::BusinessNames::STORE
          Buybid::Seller.store
        else
          Buybid::Seller.all
        end

        # set default sort in created at with desc
        params[:q][:s] ||= 'created_at desc'
        
        #================================
        @q = @seller.ransack(params[:q])
        @sellers = @q.result.all
        #================================
        
        if params[:q][:account_code].present?
          @sellers = @sellers.where(account_code: params[:q][:account_code])
        end

        # filter with visible
        if params[:q][:visible] == '1'
          @sellers = @sellers.visible
        elsif params[:q][:visible] == '2'
          @sellers = @sellers.not_visible
        end

        # filter with popular
        if params[:q][:popular] == '1'
          @sellers = @sellers.popular
        elsif params[:q][:popular] == '2'
          @sellers = @sellers.not_popular
        end

        # filter with main category id
        if params[:q][:main_category_id].present?
          @sellers = @sellers.where(main_category_id: params[:q][:main_category_id])
        end

        @sellers = @sellers.page(params[:page]).per(params[:per_page])
        @sellers_count = @sellers.where(is_deleted: 0).to_a.count
      end

      def set_seller
        @seller = Buybid::Seller.find(params[:id])
      end

      def set_contact
        @contact = Spree::Address.find(params[:contact_id])
      end

      def set_list_type
        if params[:list_type].present?
          @list_type = if params[:list_type][-1] != 's'
            params[:list_type] << 's'
          else
            params[:list_type]
          end
        elsif @seller.present?
          if @seller.auction?
            @list_type = BuybidCommon::BusinessNames::AUCTION
          elsif @seller.shop?
            @list_type = BuybidCommon::BusinessNames::SHOP
          elsif @seller.partner?
            @list_type = BuybidCommon::BusinessNames::PARTNER
          else
            @list_type = BuybidCommon::BusinessNames::ALL
          end
        else
          @list_type = BuybidCommon::BusinessNames::ALL
        end
        @list_type
      end

buybid_admin/app/helpers/admin/buybid/sellers_helper.rb
module Admin::Buybid::SellersHelper
  def display_seller_contact_title(contact, index)
    "Contact " + index.to_s + ": " + contact.firstname + " " + contact.lastname
  end

  def available_provinces
    provinces = Spree::Country.find_by(iso: "JP").states
  end

  def style_deleted(seller)
    "color:red" if seller.is_deleted?
  end

  def all?(list_type)
    false if list_type.nil?
    list_type.chomp('s') == BuybidCommon::BusinessNames::ALL
  end

  def auction?(list_type)
    false if list_type.nil?
    list_type.chomp('s') == BuybidCommon::BusinessNames::AUCTION
  end

  def shop?(list_type)
    false if list_type.nil?
    list_type.chomp('s') == BuybidCommon::BusinessNames::SHOP
  end

  def partner?(list_type)
    false if list_type.nil?
    list_type.chomp('s') == BuybidCommon::BusinessNames::PARTNER
  end

  def store?(list_type)
    false if list_type.nil?
    list_type.chomp('s') == BuybidCommon::BusinessNames::STORE
  end

  def show_category_name(seller)
    Spree::Taxon.find(seller.main_category_id).name if Spree::Taxon.exists?(seller.main_category_id)
  end

  # Show the seller logo
  def show_logo(seller, size: nil)
    logo = seller.spree_image
    link_to image_tag( main_app.url_for(logo.url(:size))), main_app.url_for(logo.url(:size)) if logo.present?
  end
  # Define the style of the button
  def button_style(setting, seller = nil)
    if (setting == :visible)
      return seller.visible? ? "btn btn-primary btn-sm" : "btn btn-danger btn-sm"
    elsif (setting == :popular)
      return seller.popular? ? "btn btn-primary btn-sm" : "btn btn-danger btn-sm"
    else (setting == :deleted)
      return "btn btn-danger btn-sm"
    end
  end

  # Define the icon of the button (Using twitter-bootstrap-rails gem)
  def button_icon(setting, seller = nil)
    if (setting == :visible)
      return seller.visible? ? "glyphicon glyphicon-ok" : "glyphicon glyphicon-remove"
    elsif (setting == :popular )
      return seller.popular? ? "glyphicon glyphicon-ok"  : "glyphicon glyphicon-remove"
    elsif (setting == :deleted)
      return "glyphicon glyphicon-remove"
    end
  end

  def image_button_style(seller, image)
    logo = seller.spree_image
    logo.id == image.id ? "btn btn-primary btn-sm" : "btn btn-danger btn-sm"
  end

  def image_button_icon(seller,image)
    logo = seller.spree_image
    logo.id == image.id ? "glyphicon glyphicon-ok" : "glyphicon glyphicon-remove "
  end

  def seller_category_taxon_ids(seller)
    seller.category_taxon_ids if seller.category_taxon_ids.present?
  end

  # Used to repopulate the field at new when validation fails
  def seller_params(params, attribute: nil)
    params[:attribute] if params.present? && params[:attribute].present?
  end

  def seller_check(seller, attr)
    return true if seller.attr?
  end

  #Show create time using the current time zone, will use the current time zone as default
  def show_created_time(created_at, format)
    created_at.in_time_zone('Asia/Bangkok').strftime(format)
  end
end

buybid_admin/app/views/buybid/admin/sellers/contacts.html.erb
<%= render partial: 'buybid/admin/shared/seller_tabs', locals: {current: :contacts}%>

<%= content_for :page_title do%>
    Contacts
<% end%>

<%= content_for :page_actions do%>
    <%= button_link_to I18n.t('seller.contact.new'), new_contact_admin_seller_path(@seller, @list_type), {class: 'btn btn-success', id: 'new-admin-seller-contact', icon: 'add'} %>
<% end %>

<%= content_for :table_filter do%>
<% end%>


<% content_for :listing_sellers_contact do %>
<table class = 'table' id = 'listing-sellers-contact'>
    <thead>
        <tr data-hook = 'admin-class-seller-contacts-header'>
            <th> <%= I18n.t('seller_contact.first_name') %> </th>
            <th> <%= I18n.t('seller_contact.last_name') %> </th>
            <th> <%= I18n.t('seller_contact.zip_code') %> </th>
            <th> <%= I18n.t('seller_contact.address1') %> </th>
            <th> <%= I18n.t('seller_contact.address2') %> </th>
            <th> <%= I18n.t('seller_contact.city') %> </th>
            <th> <%= I18n.t('seller_contact.country') %> </th>
            <th> <%= I18n.t('seller_contact.state') %> </th>
            <th> <%= I18n.t('seller_contact.phone') %> </th>
        </tr>
    </thead>

    <tbody>
        <%address_index = 1%>
        <% @contacts.each do |contact| %>
            <td class = "seller-contact-first-name"> <%=contact.firstname %> </td>
            <td class = "seller-contact-last-name"> <%=contact.lastname %> </td>
            <td class = "seller-contact-zip-code"> <%=contact.zipcode %> </td>
            <td class = "seller-contact-address1"> <%=contact.address1 %> </td>
            <td class = "seller-contact-address2"> <%=contact.address2 %> </td>
            <td class = "seller-contact-city"> <%=contact.city %> </td>
            <td class = "seller-contact-country"> <%=contact.country %> </td>
            <td class = "seller-contact-state"> <%=contact.state %> </td>
            <td class = "seller-contact-phone"> <%=contact.phone %> </td>
            <td class="actions actions-2 text-left" datahook="admin_sellers_index_row_actions">
            </td>
        <% end%>
    </tbody>
</table>
<%end%>


<% contact_index = 1%>
<% @contacts.each do |contact| %>
    <div class="panel-group">

        <div class="panel panel-default">

            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="#collapse<%=contact_index%>"> <%=display_seller_contact_title(contact, contact_index)%></a>
                </h4>
            </div>

            <div id="collapse<%=contact_index%>" class="panel-collapse collapse">
                <%= form_for contact, url: update_contact_admin_seller_path(@seller, contact, @list_type), method: :patch do |f| %>
                    <%= render partial: 'buybid/admin/shared/contact_form', locals: {f: f, contact: contact, seller_id: @seller.id} %>
                    <div id = "button">
                        <div class="text-center">
                            <%= f.submit I18n.t('seller.actions.update'), method: :patch, class: 'btn btn-primary' %> OR
                            <%= link_to I18n.t('seller.actions.delete'), destroy_contact_admin_seller_path(@seller,contact, @list_type), method: :delete, class: 'btn btn-danger', data: {confirm: I18n.t(:delete_message) + "#{contact.firstname} #{contact.lastname}"} %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    <% contact_index = contact_index + 1 %>
<% end %>

buybid_admin/app/views/buybid/admin/sellers/edit.html.erb
<%# render partial: 'buybid/admin/shared/seller_tabs', locals: { current: :details }%>

<%= content_for :page_title do%>
  Details
<%end%>
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @seller } %>
<%= form_for @seller, url: update_admin_seller_path(@seller.id, @list_type), method: :put do |f|%>
  <%= render partial: "form", locals: {f: f}%>
  <%# f.submit "Update", {class: "btn btn-success", icon: "glyphicon glyphicon-ok" } %>
  <!-- OR  -->
  <%# button_link_to "Cancel", admin_sellers_path(@list_type) , { class: "btn btn-light", icon: "glyphicon glyphicon-remove" } %>
<% end%>

buybid_admin/app/views/buybid/admin/sellers/edit_rating_and_evals.html.erb
<%= render partial: "buybid/admin/shared/seller_tabs", locals: { current: :rating_and_evals } %>
<%= content_for :page_title do%>
    Ratings and evaluations 
<% end %>
<%= form_for @seller,  url: update_admin_seller_path(@seller, @list_type), html: { multipart: true, method: :put } do |f| %>
    <fieldset>
        <%= render partial: "buybid/admin/sellers/rating_and_evals_form", locals: {f: f} %>
    </fieldset>
<% end %>

buybid_admin/app/views/buybid/admin/sellers/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Buybid::Seller) + " / " + @list_type.capitalize if @list_type.present? %>
<% end%>

<% content_for :page_actions do%>
  <%= button_link_to(Spree.t(:new_seller), "/admin/sellers/new/#{@list_type}" , {id: "new_admin_seller", class: "btn-success", icon: "add"})%>
  <br/>
<%end%>

<%= render partial: "spree/admin/shared/index_table_options", locals: {collection: @sellers}%>

<% content_for :table_filter do%>
  <div data-hook="admin_seller_sidebar">
  <%= search_form_for [:admin, @q], url: admin_sellers_path(@list_type), method: :get do |f| %>
    <div data-hook = "admin_sellers_index_search" class = "row">

        <!-- Name -->
        <div class = "col-xs-12 col-md-12">
          <div class = "form-group">
            <%= f.label :name_cont, I18n.t('seller.name'), class: "form-title"%>
            <%= f.text_field :name_cont, size: 15, class: "form-control js-quick-search-target js-filterable"%>
          </div>
        </div>
          
        <!-- Auction -->
        <% if auction?(@list_type.chomp('s')) %>      
          <div class = "col-xs-12 col-md-12">
            <div class = "form-group">
              <%= f.label :account_code, I18n.t('seller.account_code'), class: "form-title"%>
              <%= f.text_field :account_code, size: 15 ,class: "form-control js-quick-search-target js-filterable", value: params[:q][:account_code] %>
            </div>
          </div>
        <% end %>

        <div class = "col-xs-12 col-md-12" style="padding: 0">

          <!-- Business -->
          <div class = "form-group col-xs-3 col-md-3">
            <%= f.label :business, 'business', class: "form-title"%>
            <select class="form-control" onchange="window.location.href = this.value; return false;">
              <option value="/admin/sellers/all" <%= "selected=selected" if all?(@list_type) %> >
                All
              </option>
              <option value="/admin/sellers/auctions" <%= "selected=selected" if auction?(@list_type)%> >
                Auction
              </option>
              <option value="/admin/sellers/shops" <%= "selected=selected" if shop?(@list_type) %> >
                Shop
              </option>
              <option value="/admin/sellers/partners" <%= "selected=selected" if partner?(@list_type) %> >
                Partner
              </option>
            </select>
          </div>

          <!-- Visible -->
          <div class = "form-group col-xs-3 col-md-3">
            <%= f.label :visible, I18n.t('seller.visible'), class: "form-title"%>
            <%= f.select_tag :visible, ( options_for_select([
                            ['All', 0], 
                            ['Visible', 1], 
                            ['Disable', 2]
                          ], params[:q][:visible])), name: 'q[visible]',
                          class: "form-control" %>
          </div>

          <!-- Popular -->
          <div class = "form-group col-xs-3 col-md-3">
            <%= f.label :popular, I18n.t('seller.popular'), class: "form-title"%>
            <%= f.select_tag :popular, ( options_for_select([
                            ['All', 0], 
                            ['true', 1], 
                            ['false', 2]
                          ], params[:q][:popular])), name: 'q[popular]',
                          class: "form-control" %>
          </div>

          <!-- Category -->
          <div class = "form-group col-xs-3 col-md-3">
            <%= f.label :main_category_id, 'Category', class: "form-title"%>
            <%= f.select :id, options_from_collection_for_select(
                            @seller.list_category, "id", "name", params[:q][:main_category_id]
                          ), 
                          { include_blank: true }, 
                          { :class => 'form-control', 
                            :name => 'q[main_category_id]'
                          } %>
          </div>

        </div>
      </div> 

      <div data-hook="admin_sellers_index_search_buttons" class="form-actions seller_filter_search">
        <%= button Spree.t(:search), 'search' %>
      </div>
  </div>
  <%end%>
<% end%>

<span>
  <h5 class="text-primary" style="font-style: italic;">
    Total: <b><%= @sellers_count %></b>
  </h5>
</span>

<%if @sellers.any?%>
  <table class="table" id="listing-sellers">
    <thead>
      <tr data-hook="admin-class-seller-header">
        <th><input type="checkbox" id="checkAll" onclick="toggle(this)"></th>
        <th><%=I18n.t('seller.account_code') if auction?(@list_type) %></th>
        <th><%= sort_link @q, :name, I18n.t('seller.name'), { default_order: "desc" } %></th>
        <th><%=I18n.t('seller.category') %></th>
        <th><%= sort_link @q, :position,I18n.t('seller.visible'), { default_order: "desc" } %></th>
        <th><%=I18n.t('seller.popular') %></th>
        <th style="text-align: center;"><%= sort_link @q, :created_at, { default_order: "desc" } %> </th>
        <th><%=I18n.t('seller.actions.title') %></th>
      </tr>
    </thead>

    <tbody>
      <%seller_index = 1%>
      <% @sellers.each do |seller|%>
        <% if !seller.is_deleted?%>
          <td><input type="checkbox" name="foo"></td>

          <td class= "seller-account-code"> <%= seller.account_code if auction?(@list_type)%></td>
          <td class="seller-name"> <%= link_to seller.name, edit_admin_seller_path(seller, @list_type), style: style_deleted(seller) %></td>
          <td class="seller-category"> <%= show_category_name(seller) %> </td>
          <td class="seller-visible"> <%= button_link_to("", toggle_visible_admin_seller_path(seller, @list_type), class: button_style(:visible, seller), icon: button_icon(:visible, seller)) %> <%= seller.position %> </td>
          <td class="seller-popular"> <%= button_link_to("", toggle_popular_admin_seller_path(seller, @list_type), class: button_style(:popular, seller), icon: button_icon(:popular, seller)) %> </td>
          <td class="seller-created_at">  <div style = "text-align: center"> <%= show_created_time(seller.created_at, "%d-%m-%Y")%> <br/> <%= show_created_time(seller.created_at, "%H:%M:%S")%> </div> </td>
          <td class="actions actions-2 text-left" datahook="admin_sellers_index_row_actions">
            <%= link_to_edit "Edit", url: edit_admin_seller_path(seller, @list_type), no_text:true%>
            <%= button_link_to "", "/admin/sellers/#{seller.id}", method: :delete, class: button_style(:deleted), icon: button_icon(:deleted), data: {confirm: "Are you sure you want to delete seller #{seller.name}?"} %>
          </td>
          <% seller_index=seller_index+1 %>
        </tr>
        <%end%>
      <%end%>
  </tbody>
  </table>
<% end %>

<span>
  <h5 class="text-primary" style="font-style: italic;">
    Total: <b><%= @sellers_count %></b>
  </h5>
</span>

<%= render partial: "spree/admin/shared/index_table_options", locals: {collection: @sellers}%>

buybid_admin/app/views/buybid/admin/sellers/new.html.erb
<%= content_for :page_title do%>
  <%= link_to plural_resource_name(Buybid::Seller), admin_sellers_path(@list_type) %> / New 
<%end%>
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @seller } %>
<%= form_for @seller, url: create_admin_sellers_path(@list_type), method: :post do |f|%>
  <%= render partial: "form", locals: {f: f}%>
<% end %>

buybid_admin/app/views/buybid/admin/sellers/show.html.erb
<%content_for :page_title do%>
  <% plural_resource_name(Buybid::Seller)%>
<%end%>

<%=@seller.name%>
<br/>
<%=@seller.description%>
<br/>
<%=@seller.rating_total_good%>
<br/>
<%=@seller.rating_total_bad%>
<br/>
<%=@seller.rating_is_suspended%>
<br/>
<%=@seller.rating_is_deleted%>
<br/>
<%=@seller.popular%>
<br/>
<%=@seller.visible%>
<br/>
<%=@seller.auction%>
<br/>
<%=@seller.shop%>
<br/>
<%=@seller.partner%>
<br/>